apiVersion: apps/v1
kind: Deployment
metadata:
    name: httpd-deploy
    labels:
      app: httpd
spec:
    replicas: 1
    selector:
      matchLabels:
        app: httpd
    template:
      metadata:
        name: my-webserver
        labels:
          app: httpd
      spec:
        volumes:
          - name: httpd-data
            persistentVolumeClaim:
              claimName: httpd-pvc
        containers:
          - name: httpd-con
            image: httpd:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
                name: "web-server"
            volumeMounts:
              - mountPath: "/var/www/html"
                name: httpd-data
        restartPolicy: Always
