apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "httpd-pvc"
  labels:
    name: "httpd-volume"
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  resources:
     requests:
       storage: 1Gi
